services:
  sa_api_compose:
    image: ${DOCKER_USERNAME}/suivie-academique:latest
    restart: always
    ports:
      - "8080:8089"
    networks:
      - sa_net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3308:3306"
    networks:
      - sa_net
    environment:
      MYSQL_DATABASE: suivie_academique
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

networks:
  sa_net:
    driver: bridge
