name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (Tests ignorés)
        # On ajoute -DskipTests pour ne pas exécuter les tests JUnit
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          # On s'assure que le contexte est bien la racine du projet
          context: .
          # On force le build. Push est à false tant que vous n'avez pas mis vos secrets
          push: false
          tags: suivie-academique:latest
          # Cette option permet de voir les erreurs de build Docker en détail
          load: true