name: CI/CD Suivi Academique

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. RÃ©cupÃ©ration du code
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java + Cache Maven
      - name: â˜• Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Run Tests
      - name: ğŸ§ª Run Tests
        run: |
          chmod +x mvnw
          ./mvnw test

      # 4. Build Package for Docker
      - name: ğŸ“¦ Build Package
        run: |
          ./mvnw clean package -DskipTests

      # 5. Login Docker Hub
      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Setup Docker Buildx
      - name: ğŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Build et Push l'image
      - name: ğŸ³ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            Fotso12/sa-api-compose:latest
            Fotso12/sa-api-compose:${{ github.sha }}